config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/IdentityPython/pysaml2:
      branch: master
      repo: https://github.com/IdentityPython/pysaml2.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/IdentityPython/pysaml2 git:
        commands:
        - /usr/bin/env sh .sqa/script.homely-eggplant-dollar.sh
        container: qc.acc_hasty-saffron-liger
  QC.Doc:
    repos:
      github.com/IdentityPython/pysaml2 find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-charcoal-spoonbill.sh
        container: qc.doc_woolly-salmon-seahorse
      github.com/IdentityPython/pysaml2 git:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-burgundy-tarantula.sh
        container: qc.doc_jumpy-purple-snail
      github.com/IdentityPython/pysaml2 markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-heliotrope-clam.sh
        container: qc.doc_leaky-alizarin-zebu
      github.com/IdentityPython/pysaml2 restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-lilac-bonobo.sh
        container: qc.doc_flabby-pear-angora
  QC.Lic:
    repos:
      github.com/IdentityPython/pysaml2 licensee:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-wisteria-coral.sh
        container: qc.lic_shaky-black-neanderthal
  QC.Sec:
    repos:
      github.com/IdentityPython/pysaml2 bandit:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-red-buzzard.sh
        container: qc.sec_craggy-cerise-stingray
  QC.Sty:
    repos:
      github.com/IdentityPython/pysaml2 flake8:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-tomato-tiger.sh
        container: qc.sty_lovely-coral-beetle
  QC.Ver:
    repos:
      github.com/IdentityPython/pysaml2 get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-coral-akbash.sh
        container: qc.ver_snoopy-orchid-penguin
timeout: 5400
