config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/IdentityPython/pysaml2:
      branch: master
      repo: https://github.com/IdentityPython/pysaml2.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/IdentityPython/pysaml2 git:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-orchid-discus.sh
        container: qc.acc_gimpy-pumpkin-chamois
  QC.Doc:
    repos:
      github.com/IdentityPython/pysaml2 find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-russet-dane.sh
        container: qc.doc_hilly-grey-peccary
      github.com/IdentityPython/pysaml2 git:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-sepia-rottweiler.sh
        container: qc.doc_sickly-white-ragdoll
      github.com/IdentityPython/pysaml2 markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-lime-nightingale.sh
        container: qc.doc_lumpy-turquoise-wasp
      github.com/IdentityPython/pysaml2 restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-thistle-tzu.sh
        container: qc.doc_smelly-harlequin-burmese
  QC.Lic:
    repos:
      github.com/IdentityPython/pysaml2 licensee:
        commands:
        - /usr/bin/env sh .sqa/script.homely-ochre-stoat.sh
        container: qc.lic_stealthy-rose-markhor
  QC.Sec:
    repos:
      github.com/IdentityPython/pysaml2 bandit:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-brass-wolverine.sh
        container: qc.sec_whiny-periwinkle-seahorse
  QC.Sty:
    repos:
      github.com/IdentityPython/pysaml2 flake8:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-rose-raccoon.sh
        container: qc.sty_breezy-tan-angora
  QC.Ver:
    repos:
      github.com/IdentityPython/pysaml2 get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-coral-flamingo.sh
        container: qc.ver_ready-buff-weasel
timeout: 5400
