config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/IdentityPython/pysaml2:
      branch: master
      repo: https://github.com/IdentityPython/pysaml2.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/IdentityPython/pysaml2 git:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-harlequin-woodpecker.sh
        container: qc.acc_scummy-denim-baboon
  QC.Doc:
    repos:
      github.com/IdentityPython/pysaml2 find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-teal-moth.sh
        container: qc.doc_crabby-ecru-fish
      github.com/IdentityPython/pysaml2 git:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-thistle-seahorse.sh
        container: qc.doc_tacky-yellow-ocelot
      github.com/IdentityPython/pysaml2 markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-orange-schnauzer.sh
        container: qc.doc_scaly-firebrick-moth
      github.com/IdentityPython/pysaml2 restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-heliotrope-shrew.sh
        container: qc.doc_hasty-puce-crocodile
  QC.Lic:
    repos:
      github.com/IdentityPython/pysaml2 licensee:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-chocolate-opossum.sh
        container: qc.lic_slaphappy-amaranth-pig
  QC.Sec:
    repos:
      github.com/IdentityPython/pysaml2 bandit:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-cream-mayfly.sh
        container: qc.sec_stinky-tangerine-forest
  QC.Sty:
    repos:
      github.com/IdentityPython/pysaml2 flake8:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-sepia-yak.sh
        container: qc.sty_lumpy-denim-lizard
  QC.Ver:
    repos:
      github.com/IdentityPython/pysaml2 get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-amber-argentino.sh
        container: qc.ver_foggy-chocolate-bordeaux
timeout: 5400
